# Connection
# TODO: Update with your actual Postgres connection string
db-uri = "postgres://postgres:School30332319!!!@host.docker.internal:5432/shs"

# Anonymous DB role for unauthenticated requests
db-anon-role = "web_anon"

# Expose these schemas (first is default for requests)
db-schemas = "public"

# Server
server-port = 3000

# (optional) logs
# log-level = "info"

jwt-secret-is-base64 = true
jwt-secret = "hx2eKidytOUnkc67dvW8D1Ut4Dqm02mse2G5HbGreOzanQlxga9tt9GCRSDp7+9Ki9CH2ngmZKR3Yu9/Sork0g=="