#ifndef RUNTIME_CONFIG_H
#define RUNTIME_CONFIG_H

#define DEFAULT_TELEMETRY_INTERVAL_MS 1000
#define NETWORK_STABILITY_DELAY_MS 2000
#define MAX_RECONNECT_FAILURES 3
#define WIFI_CONNECT_TIMEOUT_MS 20000
#define WDT_TIMEOUT_MS 30000

#endif
