// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4UZIm2Bitcum9MYpXlQE2JkKoIb9IxGM',
    appId: '1:1064194413913:web:327e326329ad56e228a848',
    messagingSenderId: '1064194413913',
    projectId: 'smart-handicap-sign',
    authDomain: 'smart-handicap-sign.firebaseapp.com',
    storageBucket: 'smart-handicap-sign.firebasestorage.app',
    measurementId: 'G-5VYQ3B7EKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuyoIl6Uu9eVm7VACHGBqsyxbHQMVAeOg',
    appId: '1:1064194413913:android:489b7c9d22ebe0d728a848',
    messagingSenderId: '1064194413913',
    projectId: 'smart-handicap-sign',
    storageBucket: 'smart-handicap-sign.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv8zYgG_43Uc_jjwLbp7xSdHXn7XHi7fQ',
    appId: '1:1064194413913:ios:030b9b06094f477628a848',
    messagingSenderId: '1064194413913',
    projectId: 'smart-handicap-sign',
    storageBucket: 'smart-handicap-sign.firebasestorage.app',
    iosBundleId: 'com.example.smartHandicapSignApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv8zYgG_43Uc_jjwLbp7xSdHXn7XHi7fQ',
    appId: '1:1064194413913:ios:030b9b06094f477628a848',
    messagingSenderId: '1064194413913',
    projectId: 'smart-handicap-sign',
    storageBucket: 'smart-handicap-sign.firebasestorage.app',
    iosBundleId: 'com.example.smartHandicapSignApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4UZIm2Bitcum9MYpXlQE2JkKoIb9IxGM',
    appId: '1:1064194413913:web:e3432ddc60dcc95a28a848',
    messagingSenderId: '1064194413913',
    projectId: 'smart-handicap-sign',
    authDomain: 'smart-handicap-sign.firebaseapp.com',
    storageBucket: 'smart-handicap-sign.firebasestorage.app',
    measurementId: 'G-LBP4Z5498T',
  );

}