"""empty message

Revision ID: 8bd0c1febcad
Revises: 6658c57fe688
Create Date: 2025-10-22 17:41:51.358656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd0c1febcad'
down_revision = '6658c57fe688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('READY', 'DISCONNECTED', 'ERROR', 'AWAITING_ASSISTANCE', name='sign_status'), server_default='DISCONNECTED', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signs')
    # ### end Alembic commands ###
